### ISSUE TITLE
Print functionality not working

### ISSUE THREAD

**Issue by shamrt** [webpro/reveal-md#86]
I've tried installing PhantomJS locally and globally (both `phantomjs` and `phantomjs-prebuilt`), but I get the following console message regardless:

```shell
$ reveal-md slides.md --print slides.pdf
Attempting to print "slides.md" to filename "slides.pdf" as PDF.
Make sure to have PhantomJS installed (and in your path).
undefined
```

**Comment by shamrt** [comment]
Great work, by the way!

**Comment by webpro** [comment]
Are you sure the phantomjs binary is in your path?

**Comment by ncoghlan** [comment]
Thanks for reveal-md - it finally got me to upgrade from the software I was previously using to reveal.js :)

However, I'm seeing the same error message as @shamrt when attempting to print to PDF. Component version details:

```
$ reveal-md -V
0.0.32
$ phantomjs --version
2.1.1
$ PhantomJS --version
2.1.1
```

Both `phantomjs` and `PhantomJS` are symlinks to a user-level installation of `phantomjs-prebuilt`.

**Comment by ncoghlan** [comment]
I can also note that I got tracebacks rather than an undefined result when:

1. PhantomJS was missing
2. The display server was already running (and hence occupying the default local port)

**Comment by ncoghlan** [comment]
Further data point: I'm using the YAML header feature to specify a title and theme:

```
---
title: Opportunities in Open Collaboration
theme: css/theme/white.css
---
```

When rendering with --static, reveal-md gets confused and treats that as part of the opening slide.

However, fixing that didn't fix the printing problem, so I filed a separate issue for the challenges I ran into with --static: https://github.com/webpro/reveal-md/issues/87

**Comment by webpro** [comment]
FYI, I'm working on a complete rewrite of reveal-md, and I will take open tickets into account.

**Comment by webpro** [comment]
@shamrt @ncoghlan I've just released v0.1.0, could you please try again with the latest version? I have no idea if this fixes anything in this regard, but at least things should be easier to debug from now on.

**Comment by palexster** [comment]
I am also affected, having the same error message of @shamrt  and @ncoghlan 
```
$ reveal-md --version                    
0.1.1
$ phantomjs --version
2.1.1
```
By the way, a very good work!

**Comment by webpro** [comment]
@shamrt @ncoghlan Are you on *nux or Windows? I'm on MacOS, can't easily debug on something else.

**Comment by shamrt** [comment]
I'm using MacOS. I'm not getting the `undefined` error anymore, but the printed slides are blank.

Here's the latest output log:

```
$ reveal-md slides.md --theme rbc --print slides.test.pdf
Attempting to print "slides.md" to filename "slides.test.pdf" as PDF.
Make sure to have PhantomJS installed (and in your path).
Printing PDF (Paper size: 1920x1400)
Printed successfully
```

Here are [the generated slides](https://github.com/webpro/reveal-md/files/790882/slides.test.pdf).

Thanks for your help!

**Comment by shamrt** [comment]
I should mention that, if I remove the `--theme` flag, the slides are populated. That said, the PDF doesn't render one slide per page; they tend to be grouped together.

**Comment by webpro** [comment]
* The attached generated slides seem to render just fine in the Chrome browser.
* The generated slides with `--print` don't render nicely on the print pages indeed. Unfortunately, that's an issue with reveal.js itself. I've checked and things work fine with the current master/dev branch of the reveal.js package, but the fixes aren't released yet.

**Comment by shamrt** [comment]
Okay, given that's the case, I'd say this issue is resolved. Thanks for your help!

**Comment by webpro** [comment]
Yes, I'll keep an eye on the reveal.js releases.

**Comment by n-batalha** [comment]
Still occurring randomly on the latest version.

```
$ reveal-md --version
1.1.0
$ node --version
v8.9.4
$ phantomjs --version
2.1.1
```
The `demo/a.md` doesn't print well with the default theme but it does with beige. However even with beige on my own slides, most of the times I get an empty pdf (same command run each time).

Great tool by the way!

**Comment by TypedLambda** [comment]
i have the same problem. 
```sh
$ reveal-md --version
1.1.0
$ node --version
v9.3.0
$ phantomjs --version
2.1.1
```

pdfs contain mostly an empty page with the background color.
sometimes the content gets rendered in. about 6 tries to success here.

```sh
$ uname -v
FreeBSD 12.0-CURRENT 
```
